### ISSUE TITLE
How can I install "BamCleave"?

### ISSUE THREAD

**Issue by danli349** [avaspataru/BamCleave#1]
Hello:

How can I install "BamCleave"?
Thanks

**Comment by avaspataru** [comment]
BamCleave previously developed software by dr. Nigel Dyer, University of Warwick. Please contact him for the software.

**Comment by danli349** [comment]
@avaspataru 
Thanks 
I found the source for download "https://warwick.ac.uk/research/rtp/bioinformatics/aboutus/dyer/software/bamcleave"
